# Generated by Django 6.0.4 on 2026-05-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='dni',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
