# Generated by Django 6.0.4 on 2026-05-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_perfil_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='pais',
            field=models.CharField(max_length=50),
        ),
    ]
