# Generated by Django 6.0.4 on 2026-04-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='conocer',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
