# Generated by Django 6.0.4 on 2026-05-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petra', '0002_producto_codigo_producto_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
