# Generated by Django 6.0.4 on 2026-04-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petra', '0002_historia_conocer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='historia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historia',
            name='titulo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
